"""Markdown rendering of the approval package.

The agent writes the prose version. This renders the same ten sections straight
from the stored run with no model involved - used as the fallback when Vertex
is unreachable, as what the browser displays, and as the reference the agent's
version can be checked against.

The content itself comes from render.package.build_package, so this file and
the Word writer beside it cannot disagree about what the document says.
"""
from __future__ import annotations

from .package import build_package, eur  # noqa: F401 - eur re-exported


def _table(block: dict) -> list[str]:
    numeric = set(block.get("numeric") or [])
    header = block["header"]
    align = ["---:" if i in numeric else "---" for i in range(len(header))]
    out = [
        "| " + " | ".join(str(h) for h in header) + " |",
        "|" + "|".join(align) + "|",
    ]
    for row in block["rows"]:
        out.append("| " + " | ".join(str(cell) for cell in row) + " |")
    out.append("")
    return out


def _fields(block: dict) -> list[str]:
    out = ["| | |", "|---|---|"]
    for label, value in block["rows"]:
        # A blank field is a line to sign on, not an HTML entity - the
        # renderer escapes text, so &nbsp; would print literally.
        out.append(f"| **{label}** | {value or ''} |")
    out.append("")
    return out


def _blocks(blocks: list[dict]) -> list[str]:
    out: list[str] = []
    for block in blocks:
        kind = block["type"]
        if kind == "para":
            out += [block["text"], ""]
        elif kind == "note":
            out += [f"_{block['text']}_", ""]
        elif kind == "bullets":
            out += [f"- {item}" for item in block["items"]] + [""]
        elif kind == "table":
            out += _table(block)
        elif kind == "fields":
            out += _fields(block)
        elif kind == "signature":
            out += ["Approver signature: ________________________    "
                    "Date: ________________", ""]
    return out


def render_memo(run_id: str) -> str:
    package = build_package(run_id)
    if package is None:
        return "That run could not be found."

    out: list[str] = [
        f"# {package['title']}",
        "",
        f"## {package['subtitle']} — {package['date_text']}",
        "",
    ]
    out += _fields(package["meta"])

    for section in package["sections"]:
        out += [f"## {section['number']}. {section['title']}", ""]
        out += _blocks(section["blocks"])

    out.append(
        f"_Generated by engine {package['engine_version']} on "
        f"{package['generated_at']}. Every figure above is either taken from a "
        f"supplier quotation or derived by the engine as labelled; no figure was "
        f"produced by a language model._")
    return "\n".join(out)
